import type ColorTheme from "../interfaces/ColorTheme";

export function getColorThemes(): ColorTheme[] {
    return [
        {
            backgroundCol: "#021526",
            primaryColor: "#3f6c7a",
            secondaryColor: "#03346E",
            timerSecondaryColor: "#6EACDA",
            textColor: "#E2E2B6",
            name: "Space",
        },
        {
            backgroundCol: "#F0F0F0",
            primaryColor: "#4CAF50",
            secondaryColor: "#388E3C",
            timerSecondaryColor: "#81C784",
            textColor: "#212121",
            name: "Forest",
        },
        {
            backgroundCol: "#2C3E50",
            primaryColor: "#E74C3C",
            secondaryColor: "#C0392B",
            timerSecondaryColor: "#EC7063",
            textColor: "#ECF0F1",
            name: "Crimson",
        },
        {
            backgroundCol: "#cbeef3",
            primaryColor: "#f49cbb",
            secondaryColor: "#880d1e",
            timerSecondaryColor: "#f26a8d",
            textColor: "#df3755",
            name: "Sakura",
        },
        {
            backgroundCol: "#e7f0dc",
            primaryColor: "#a5be9a",
            secondaryColor: "#597445",
            timerSecondaryColor: "#bfd7a2",
            textColor: "#004000",
            name: "Grass",
        },
        {
            backgroundCol: "#1a1a2e",
            primaryColor: "#16213e",
            secondaryColor: "#0f3460",
            timerSecondaryColor: "#e94560",
            textColor: "#eaeaea",
            name: "Midnight",
        },
        {
            backgroundCol: "#0d0d0d",
            primaryColor: "#1a1a1a",
            secondaryColor: "#2d2d2d",
            timerSecondaryColor: "#00ff99",
            textColor: "#00ff99",
            name: "Neon",
        },
        {
            backgroundCol: "#fdf6e3",
            primaryColor: "#eee8d5",
            secondaryColor: "#93a1a1",
            timerSecondaryColor: "#268bd2",
            textColor: "#657b83",
            name: "Solarized",
        },
        {
            backgroundCol: "#282828",
            primaryColor: "#3c3836",
            secondaryColor: "#504945",
            timerSecondaryColor: "#d79921",
            textColor: "#ebdbb2",
            name: "Gruvbox",
        },
        {
            backgroundCol: "#1e1e2e",
            primaryColor: "#313244",
            secondaryColor: "#45475a",
            timerSecondaryColor: "#cba6f7",
            textColor: "#cdd6f4",
            name: "Catppuccin",
        },
        {
            backgroundCol: "#011627",
            primaryColor: "#0b2942",
            secondaryColor: "#1d3b53",
            timerSecondaryColor: "#7fdbca",
            textColor: "#d6deeb",
            name: "Ocean",
        },
        {
            backgroundCol: "#fffbf5",
            primaryColor: "#fef3e2",
            secondaryColor: "#f5cba7",
            timerSecondaryColor: "#e67e22",
            textColor: "#6e3010",
            name: "Sunset",
        },
        {
            backgroundCol: "#2d1b69",
            primaryColor: "#4a2c8a",
            secondaryColor: "#7b2d8b",
            timerSecondaryColor: "#ff6ec7",
            textColor: "#f0e6ff",
            name: "Vaporwave",
        },
        {
            backgroundCol: "#f5f5f0",
            primaryColor: "#e8e8e0",
            secondaryColor: "#b0b0a8",
            timerSecondaryColor: "#555555",
            textColor: "#222222",
            name: "Paper",
        },
    ];
}